### PR TITLE
Update to 21.08.0. JB#55208

### PR DESCRIPTION
**Pull request by pvuorela**
@rainemak @chriadam @blammit @dcaliste

### CODE REVIEW

**Comment by dcaliste** [comment]
Looks good to me. It compiles properly in the SDK and then sailfish-office is also compiling (well actually failing because of the newer tracker dependency, but that's another story).

Already existing but the README and COPYING files are put in a glib-doc subpackage, which looks queer. In particular, COPYING is already part of the main package...

**Comment by pvuorela** [comment]
The whole glib-doc subpackage looks strange as it only contains couple useless README files, not the actual docs. I'm guessing it got somehow copied from fedora packaging even though we don't generate the docs on the build.

Could add a commit to just remove that.

**Comment by dcaliste** [comment]
Nice, thanks.

**Review by okodron — COMMENTED** [review]
Is `Requires: libjpeg-devel` necessary for `poppler-devel` subpackage?
Looks like libjpeg is not used for this build.

**Review by okodron — CHANGES_REQUESTED** [review]
Also it's better to use `%cmake`, `%make_build` and `%make_install` macros.

**Comment by okodron** [comment]
> Is `Requires: libjpeg-devel` necessary for `poppler-devel` subpackage?
> Looks like libjpeg is not used for this build.

Oh, didn't noticed its build requires: better to replace `BuildRequires: libjpeg-devel` with `BuildRequires: pkgconfig(libjpeg)`.

**Comment by pvuorela** [comment]
Not related to the update but good points. Did some more cleanups to the .spec.

**Review by okodron — APPROVED** [review]

**Comment by attah** [comment]
I built this and installed it on my 10 II running SFOS 4.1 (just to check SeaPrint keeps working - and it does).
But just by chance i found that now it is near-impossible to trigger the select/copy function on PDFs in sailfish-office.
Is it just me?

**Comment by pvuorela** [comment]
Selecting text works fine for me

**Comment by attah** [comment]
Hmm, ok. Sorry for the noise. 
I'll do some more tests with reverting and report on the forum if i still have problems.

**Pull request merged**
